version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./.docker-workdir/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: rappellemoi-db
    ports:
      - "5432:5432"

